server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: davidwrz
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration