server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: davidwrz
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

adyen:
  url: https://checkout-test.adyen.com/v71/payments
  api-key: AQEvhmfuXNWTK0Qc+iSYl2oqrvWOTahIH4JfXWxEx1Svn8hraJ64gQ5iXQug5TyeDo0QwV1bDb7kfNy1WIxIIkxgBw==-G4N6q9q+auj9gXvSRNVxGYijOk35fUvEtaRMl0RWnPQ=-;t{@Vg6@,T.D@A^5
  merchant-account: HenriqueCerqueiraLdaECOM

jwt:
  secret-key: mW3g8ZkR
